/**
 * Git operations and PR creation for the data refresh pipeline.
 */

import { execSync } from 'child_process'
import { writeFileSync, unlinkSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'

/**
 * Build a structured changelog by comparing old and new data.
 * @param {object} oldData
 * @param {object} newData
 * @returns {{ pricing: string[], specs: string[], newVehicles: string[], tbdResolved: string[], gapsFilled: string[], otdRecalculated: number }}
 */
export function buildChangelog(oldData, newData) {
  const changes = {
    pricing: [],
    specs: [],
    newVehicles: [],
    tbdResolved: [],
    gapsFilled: [],
    otdRecalculated: 0,
  }

  const oldByName = Object.fromEntries(oldData.details.map((r) => [r.name, r]))
  const specFields = ['msrp', 'range_mi', 'hp', 'battery_kwh', 'seats', 'charging_type',
    'frunk_cu_ft', 'cargo_behind_3rd_cu_ft', 'cargo_behind_2nd_cu_ft',
    'cargo_behind_1st_cu_ft', 'cargo_floor_width_in', 'fold_flat',
    'onboard_ac_kw', 'l2_10_100', 'l2_10_80', 'self_driving',
    'car_software', 'main_display', 'additional_displays', 'audio']

  for (const row of newData.details) {
    const old = oldByName[row.name]

    if (!old) {
      // New entry
      changes.newVehicles.push(`**${row.name}** (skeleton entry added — needs human review)`)
      continue
    }

    // Pre-owned pricing changes
    if (row.preowned_range !== old.preowned_range) {
      changes.pricing.push(`**${row.name}**: ${old.preowned_range} -> ${row.preowned_range}`)
    }

    // Spec changes
    for (const field of specFields) {
      if (JSON.stringify(row[field]) !== JSON.stringify(old[field])) {
        const wasEmpty = old[field] === null || old[field] === ''
        const isTbdResolved = isTbdLike(old[field]) && !isTbdLike(row[field])
        if (wasEmpty && !isTbdLike(row[field])) {
          changes.gapsFilled.push(`**${row.name}**: \`${field}\` filled → ${row[field]}`)
        } else if (isTbdResolved) {
          changes.tbdResolved.push(`**${row.name}**: \`${field}\` resolved to ${row[field]}`)
        } else {
          changes.specs.push(`**${row.name}**: \`${field}\` ${old[field]} -> ${row[field]}`)
        }
      }
    }

    // OTD recalculated
    if (row.otd_new !== old.otd_new || row.otd_preowned !== old.otd_preowned) {
      changes.otdRecalculated++
    }
  }

  // Check preowned table too
  const oldPreownedByName = Object.fromEntries(oldData.preowned.map((r) => [r.name, r]))
  for (const row of newData.preowned) {
    const old = oldPreownedByName[row.name]
    if (old && row.preowned_range !== old.preowned_range) {
      // Only add if not already captured from details
      const existing = changes.pricing.find((p) => p.includes(row.name))
      if (!existing) {
        changes.pricing.push(`**${row.name}**: ${old.preowned_range} -> ${row.preowned_range}`)
      }
    }
  }

  return changes
}

function isTbdLike(val) {
  if (val == null) return true
  if (typeof val === 'string') {
    const lower = val.toLowerCase()
    return lower.includes('tbd') || lower.includes('n/a') || lower === '-' || lower === ''
  }
  return false
}

/**
 * Format the changelog into a PR body.
 */
export function formatPrBody(changes, cost) {
  const sections = []

  if (changes.pricing.length) {
    sections.push(`### Pre-owned Pricing Updates\n${changes.pricing.map((c) => `- ${c}`).join('\n')}`)
  }
  if (changes.tbdResolved.length) {
    sections.push(`### TBD Fields Resolved\n${changes.tbdResolved.map((c) => `- ${c}`).join('\n')}`)
  }
  if (changes.specs.length) {
    sections.push(`### Spec Corrections\n${changes.specs.map((c) => `- ${c}`).join('\n')}`)
  }
  if (changes.gapsFilled.length) {
    sections.push(`### Data Gaps Filled\n${changes.gapsFilled.map((c) => `- ${c}`).join('\n')}`)
  }
  if (changes.newVehicles.length) {
    sections.push(`### New Vehicles Detected\n${changes.newVehicles.map((c) => `- ${c}`).join('\n')}`)
  }
  if (changes.otdRecalculated > 0) {
    sections.push(`### OTD Recalculations\n${changes.otdRecalculated} entries had OTD values recalculated.`)
  }

  if (sections.length === 0) {
    sections.push('No significant changes detected in this refresh cycle.')
  }

  return `## Monthly EV Data Refresh\n\n${sections.join('\n\n')}\n\n---\n*Generated by automated pipeline. All changes require human review before merging.*\n*Estimated API cost this run: ~$${cost.toFixed(2)}*`
}

/**
 * Create a git branch, commit, push, and open a PR.
 * @param {string} jsonPath - Path to the updated ev-data.json
 * @param {string} prBody - The PR description
 */
export function createPR(jsonPath, prBody) {
  const date = new Date().toISOString().slice(0, 10)
  const branch = `data-refresh/${date}`
  const title = `chore(data): monthly refresh ${date}`

  const run = (cmd) => execSync(cmd, { stdio: 'pipe', encoding: 'utf-8' }).trim()

  // Configure git for CI environment
  try {
    run('git config user.name "EV Data Bot"')
    run('git config user.email "ev-data-bot@users.noreply.github.com"')
  } catch {
    // May already be configured
  }

  // Clean up any existing branch (from a previous failed run)
  try {
    run(`git branch -D ${branch}`)
    console.log(`Deleted existing local branch: ${branch}`)
  } catch { /* branch doesn't exist locally — fine */ }
  try {
    run(`git push origin --delete ${branch}`)
    console.log(`Deleted existing remote branch: ${branch}`)
  } catch { /* branch doesn't exist on remote — fine */ }

  console.log(`Creating branch: ${branch}`)
  run(`git checkout -b ${branch}`)

  console.log('Staging ev-data.json...')
  run(`git add "${jsonPath}"`)

  console.log('Committing...')
  run(`git commit -m "${title}"`)

  console.log('Pushing...')
  run(`git push -u origin ${branch}`)

  console.log('Creating PR...')
  // Write PR body to a temp file to avoid shell escaping issues
  const tmpFile = join(tmpdir(), 'pr-body.md')
  writeFileSync(tmpFile, prBody)
  try {
    const prUrl = run(`gh pr create --title "${title}" --body-file "${tmpFile}" --base master`)
    console.log(`PR created: ${prUrl}`)
    return prUrl
  } finally {
    try { unlinkSync(tmpFile) } catch { /* ignore */ }
  }
}
